#[derive(Debug, Clone, PartialEq)]
pub enum LispError {
	INVALID_ARGUMENT_TYPE,
	NOT_ENOUGH_ARGUMENTS,
	TOO_MANY_ARGUMENTS,
	UNBOUND_VARIABLE,
	INVALID_FORM,
	UNKNOWN_FUNCTION,
	INVALID_ARG_LIST,
	MISMATCHED_BRACKETS
}