#[derive(Debug, Clone, PartialEq)]
#[allow(non_camel_case_types)]
pub enum LispError {
	INVALID_ARGUMENT_TYPE,
	NOT_ENOUGH_ARGUMENTS,
	TOO_MANY_ARGUMENTS,
	UNBOUND_VARIABLE,
	INVALID_FORM,
	UNKNOWN_FUNCTION,
	INVALID_ARG_LIST,
	MISMATCHED_BRACKETS,
	NOT_YET_IMPLEMENTED,
	NO_INPUT
}